# Generated by Django 3.1.2 on 2020-10-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20201015_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_From',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_Flags',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_Twitches',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
